name: windows

on:
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/macos.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/precompile.yml'
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '.github/workflows/macos.yml'
      - '.github/workflows/linux.yml'
      - '.github/workflows/precompile.yml'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: "!contains(github.event.pull_request.labels.*.name, 'skip ci')"
    runs-on: windows-latest
    name: Windows x64 - OTP 26

    steps:
      - uses: actions/checkout@v3

      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26"
          elixir-version: "1.15"

      - uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: "x64"

      - name: Install rebar3
        shell: bash
        run: |
          curl -fSL https://s3.amazonaws.com/rebar3/rebar3 -o rebar3 && chmod +x rebar3
          cat <<EOF >rebar3.cmd
          @echo off
          setlocal
          set rebarscript=%~f0
          escript.exe "%rebarscript:.cmd=%" %*
          EOF

      - name: rebar3 compile
        shell: bash
        run: |
          export PATH="$(pwd):$PATH"

          rebar3 deps
          rebar3 compile

      - name: EUnit Test
        shell: bash
        run: |
          export PATH="$(pwd):$PATH"

          rebar3 eunit
